version: '3.8'

services:
  financial-advisor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-advisor-app
    ports:
      - "8080:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    depends_on:
      - umami

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT:-replace-me-with-a-random-string}
      NODE_ENV: production
    depends_on:
      - umami-db
    restart: unless-stopped

  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  umami-db-data:
